### ISSUE TITLE
Error when obfuscating code

### ISSUE THREAD

**Issue by jewmberzoom** [WannaBeSkid/DisLog-Discord-Token-Logger#1]
Hello. I was trying to set this up and everything was going fine until I tried to obfuscate the code. it gave me this error:
`INFO     PyArmor Trial Version 6.6.2
INFO     Target platforms: Native
INFO     Source path is "C:\Users\Owner\DisLog-Token-Logger"
INFO     Entry scripts are ['DisLog.py']
INFO     Use cached capsule C:\Users\Owner\.pyarmor\.pyarmor_capsule.zip
INFO     Search scripts mode: Normal
INFO     Save obfuscated scripts to "dist"
INFO     Read product key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced value is 0
INFO     Super mode is False
INFO     Generating runtime files to dist\pytransform
INFO     Extract pytransform.key
INFO     Generate default license file
INFO     Copying c:\users\owner\appdata\local\programs\python\python35\lib\site-packages\pyarmor\platforms\windows\x86_64\_pytransform.dll
INFO     Patch library dist\pytransform\_pytransform.dll
INFO     Patch library file OK
INFO     Copying c:\users\owner\appdata\local\programs\python\python35\lib\site-packages\pyarmor\pytransform.py
INFO     Rename it to pytransform/__init__.py
INFO     Generate runtime files OK
INFO     Start obfuscating the scripts...
INFO            DisLog.py -> dist\DisLog.py
ERROR    invalid syntax (<frozen DisLog>, line 13)`
Note that I did nothing with the code, all I did was paste in the webhook.

**Comment by WannaBeSkid** [comment]
Trying updating to python Python 3.8

**Comment by jewmberzoom** [comment]
I'm on python 3.8.

**Comment by jewmberzoom** [comment]
nevermind, i still had version 3.5 in my PATH
